service: CountryService
frameworkVersion: '3'

plugins:
  - serverless-prune-plugin
  - serverless-offline

provider:
  name: aws
  runtime: ruby3.2
  stage: prod
  region: ap-south-1
  environment:
    countries_api_domain: restcountries.com
    countries_api_version: 3.1

custom:
  prune:
    automatic: true
    number: 3

functions:
  - ${file(lambda.yml)}